/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.software_engineering;

import com.mysql.cj.protocol.Resultset;
import java.awt.Component;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author addie
 */
public class login_form extends javax.swing.JFrame {
    private static Component frame;
    /**
     * Creates new form login_form
     */
    public login_form() {
        initComponents();
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login | Prisoner's Visitor and Good Morale Time Allowance");
        setBackground(new java.awt.Color(0, 53, 84));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 53, 84));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(255, 250, 202));
        txt_username.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 185, 35));

        txt_password.setBackground(new java.awt.Color(255, 250, 202));
        txt_password.setForeground(new java.awt.Color(0, 0, 0));
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 185, 35));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        btn_login.setBackground(new java.awt.Color(103, 146, 137));
        btn_login.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 80, -1));

        logo.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\system\\images\\pnp_logo.png"));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 190, 266));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        
        //String sql = "INSERT INTO login_credentials(usernames,passwords) VALUES (?,?)";
        
//        try{
//            PreparedStatement statement = sql_connect.db_connect().prepareStatement(sql);
//            statement.setString(1, txt_username.getText());
//            statement.setString(2, adminPassEncrypt.encryptPassword(txt_password.getText()));
//            
//            statement.executeUpdate();
//            
//            JOptionPane.showMessageDialog(frame, "added!");
//        }catch(SQLException e){
//            System.out.print(e);
//            
//        } catch (NoSuchAlgorithmException ex) {
//            Logger.getLogger(login_form.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
        
        
        String sql = "SELECT passwords FROM login_credentials WHERE usernames = ?";
        variable.adminPassword = txt_password.getText();
        variable.adminUsername = txt_username.getText();
        
        
        try{
            
            PreparedStatement statement = sql_connect.db_connect().prepareStatement(sql);
            
            statement.setString(1,variable.adminUsername);
            
            ResultSet resultSet = statement.executeQuery();
            
            
            if(txt_password.getText().isEmpty() || txt_username.getText().isEmpty()){
                JOptionPane.showMessageDialog(frame, "All fields must be filled!");
            }else{
                if(resultSet.next()){
                   variable.hashedPasscode = resultSet.getString("passwords");
                }

                try{
                    if(adminPassEncrypt.encryptPassword(variable.adminPassword).equals(variable.hashedPasscode)){
                        JOptionPane.showMessageDialog(frame, "Welcome!");  
                        welcome_form form = new welcome_form();
                        form.show();
                        show(false);
                    }else{
                        JOptionPane.showMessageDialog(frame, "Invalid Username or Password!");
                    }
                }catch(NoSuchAlgorithmException e){
                    System.out.print(e);
                }
            }
        }
        catch(SQLException ex){
            System.out.println(ex);
        }
        
        
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
       String sql = "SELECT passwords FROM login_credentials WHERE usernames = ?";
        variable.adminPassword = txt_password.getText();
        variable.adminUsername = txt_username.getText();
        
        
        try{
            
            PreparedStatement statement = sql_connect.db_connect().prepareStatement(sql);
            
            statement.setString(1,variable.adminUsername);
            
            ResultSet resultSet = statement.executeQuery();
            
            
            if(txt_password.getText().isEmpty() || txt_username.getText().isEmpty()){
                JOptionPane.showMessageDialog(frame, "All fields must be filled!");
            }else{
                if(resultSet.next()){
                   variable.hashedPasscode = resultSet.getString("passwords");
                }

                try{
                    if(adminPassEncrypt.encryptPassword(variable.adminPassword).equals(variable.hashedPasscode)){
                        JOptionPane.showMessageDialog(frame, "Welcome!");  
                        welcome_form form = new welcome_form();
                        form.show();
                        show(false);
                    }else{
                        JOptionPane.showMessageDialog(frame, "Invalid Username or Password!");
                        txt_username.setText("");
                        txt_password.setText("");
                    }
                }catch(NoSuchAlgorithmException e){
                    System.out.print(e);
                }
            }
        }
        catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_txt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    public static javax.swing.JPasswordField txt_password;
    public static javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
