/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.software_engineering;

import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author addie
 */
public class Prisoner_Form extends javax.swing.JFrame {

    /**
     * Creates new form Prisoner_Form
     */
    public Prisoner_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pfirstName = new javax.swing.JTextField();
        pmiddleName = new javax.swing.JTextField();
        pSurname = new javax.swing.JTextField();
        pAge = new javax.swing.JTextField();
        pGmta = new javax.swing.JTextField();
        pGender = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 53, 84));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\system\\images\\small_logo.png"));
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 6, 120, 140));

        jPanel8.setBackground(new java.awt.Color(255, 250, 202));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Add Prisoner");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("First Name:");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 130, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Middle Name:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 150, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Surname:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 100, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Age:");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 67, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Prisoner's Sentence (in months):");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 290, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Gender:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 80, 30));

        pfirstName.setBackground(new java.awt.Color(255, 250, 202));
        pfirstName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pfirstName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(pfirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 240, 30));

        pmiddleName.setBackground(new java.awt.Color(255, 250, 202));
        pmiddleName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pmiddleName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(pmiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 240, 30));

        pSurname.setBackground(new java.awt.Color(255, 250, 202));
        pSurname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pSurname.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(pSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 240, 30));

        pAge.setBackground(new java.awt.Color(255, 250, 202));
        pAge.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pAge.setForeground(new java.awt.Color(0, 0, 0));
        pAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAgeActionPerformed(evt);
            }
        });
        jPanel7.add(pAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 60, 30));

        pGmta.setBackground(new java.awt.Color(255, 250, 202));
        pGmta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pGmta.setForeground(new java.awt.Color(0, 0, 0));
        pGmta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pGmtaActionPerformed(evt);
            }
        });
        jPanel7.add(pGmta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 80, 30));

        pGender.setBackground(new java.awt.Color(255, 250, 202));
        pGender.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pGender.setForeground(new java.awt.Color(0, 0, 0));
        pGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        pGender.setSelectedIndex(-1);
        jPanel7.add(pGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 80, 30));

        jButton6.setBackground(new java.awt.Color(103, 146, 137));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, 30));

        jButton7.setBackground(new java.awt.Color(103, 146, 137));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Submit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 110, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pGmtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pGmtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pGmtaActionPerformed

    private void pAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pAgeActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        goodTimeMoral gtm = new goodTimeMoral();
        gtm.show();
        show(false);
    }//GEN-LAST:event_jButton6ActionPerformed
    Component frame;
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        variable.pFirstname = pfirstName.getText().toUpperCase();
        variable.pMiddlename = pmiddleName.getText().toUpperCase();
        variable.pSurname = pSurname.getText().toUpperCase();
        variable.pAge = pAge.getText();
        variable.pGender = (String) pGender.getSelectedItem();
        
        try{
            int age = Integer.parseInt(variable.pAge);
            int sentence = Integer.parseInt(pGmta.getText());
            
            boolean isExisting = true;
        
            String sql = "SELECT * FROM prisoners where prisoner_first_name = ? and prisoner_middle_name = ? and prisoner_surname = ?";
            String sql1 = "INSERT INTO prisoners (prisoner_first_name, prisoner_middle_name, prisoner_surname,age,gender,isAvailable,gmta_status,is_ready) VALUES (?,?,?,?,?,?,?,?)";

            try{
                PreparedStatement statement = (PreparedStatement) sql_connect.db_connect().prepareStatement(sql);

                statement.setString(1, variable.pFirstname);
                statement.setString(2, variable.pMiddlename);
                statement.setString(3, variable.pSurname);

                ResultSet resultSet = statement.executeQuery();

                if(resultSet.next()){
                    isExisting = true;
                }else{
                    isExisting= false;
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,
                    "There's a problem in the database.",
                    "Database Error",
                    JOptionPane.WARNING_MESSAGE);
            }

            if(pfirstName.getText().toUpperCase().isEmpty() 
                    || pmiddleName.getText().toUpperCase().isEmpty()
                    || pSurname.getText().toUpperCase().isEmpty()
                    || pAge.getText().isEmpty()
                    || variable.pGender.isEmpty()){
                JOptionPane.showMessageDialog(frame, 
                                    "All fields must be filled!");
            }else{
                if(!isExisting){

                    try{
                    PreparedStatement statement = (PreparedStatement) sql_connect.db_connect().prepareStatement(sql1);

                    statement.setString(1, variable.pFirstname);
                    statement.setString(2,variable.pMiddlename);
                    statement.setString(3,variable.pSurname);
                    statement.setString(4,variable.pAge);
                    statement.setString(5,variable.pGender.toUpperCase());
                    statement.setBoolean(6,true);
                    statement.setInt(7, sentence);
                    statement.setBoolean(8,false);

                    statement.executeUpdate();

                    JOptionPane.showMessageDialog(frame, 
                                    "Information added successfully!");

                    pfirstName.setText("");
                    pmiddleName.setText("");
                    pSurname.setText("");
                    pAge.setText("");
                    pGender.setSelectedItem(null);
                    pGmta.setText("");
                    
                }catch (SQLException e){
                    System.out.println(e);
                }

                }else{
                    JOptionPane.showMessageDialog(frame, 
                                    "Prisoner information already exist!");
                    pfirstName.setText("");
                    pmiddleName.setText("");
                    pSurname.setText("");
                    pAge.setText("");
                    pGender.setSelectedItem(null);
                    pGmta.setText("");
                }
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(frame, 
                "Age or prisoner's sentence should be number only!",
                "Invalid input",
                JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prisoner_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prisoner_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prisoner_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prisoner_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prisoner_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField pAge;
    private javax.swing.JComboBox<String> pGender;
    private javax.swing.JTextField pGmta;
    private javax.swing.JTextField pSurname;
    private javax.swing.JTextField pfirstName;
    private javax.swing.JTextField pmiddleName;
    // End of variables declaration//GEN-END:variables
}
