/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.software_engineering;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author addie
 */
public class visitorProfile extends javax.swing.JFrame {

    /**
     * Creates new form visitorProfile
     */
    public visitorProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstnameTxt = new javax.swing.JTextField();
        surnameTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        contactTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        middlenameTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JComboBox<>();
        isEligible = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 53, 84));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstnameTxt.setEditable(false);
        firstnameTxt.setBackground(new java.awt.Color(255, 250, 202));
        firstnameTxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        firstnameTxt.setForeground(new java.awt.Color(0, 0, 0));
        firstnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(firstnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 240, 40));

        surnameTxt.setEditable(false);
        surnameTxt.setBackground(new java.awt.Color(255, 250, 202));
        surnameTxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        surnameTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(surnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 240, 40));

        ageTxt.setEditable(false);
        ageTxt.setBackground(new java.awt.Color(255, 250, 202));
        ageTxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ageTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 61, 40));

        contactTxt.setEditable(false);
        contactTxt.setBackground(new java.awt.Color(255, 250, 202));
        contactTxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        contactTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(contactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 240, 40));

        addressTxt.setEditable(false);
        addressTxt.setBackground(new java.awt.Color(255, 250, 202));
        addressTxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addressTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 240, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Surname :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Is Eligible :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Age :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact No. :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jButton1.setBackground(new java.awt.Color(103, 146, 137));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 70, 30));

        jButton2.setBackground(new java.awt.Color(103, 146, 137));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 110, 38));

        editBtn.setBackground(new java.awt.Color(103, 146, 137));
        editBtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.setToolTipText("");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 110, 38));

        jLabel10.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\system\\images\\small_logo.png"));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 120, 140));

        jPanel4.setBackground(new java.awt.Color(255, 250, 202));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Visitor Profile");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 680, 110));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Middle Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        middlenameTxt.setEditable(false);
        middlenameTxt.setBackground(new java.awt.Color(255, 250, 202));
        middlenameTxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        middlenameTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(middlenameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 240, 40));

        genderTxt.setBackground(new java.awt.Color(255, 250, 202));
        genderTxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        genderTxt.setForeground(new java.awt.Color(0, 0, 0));
        genderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        genderTxt.setSelectedIndex(-1);
        genderTxt.setEnabled(false);
        jPanel1.add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 100, 40));

        isEligible.setBackground(new java.awt.Color(255, 250, 202));
        isEligible.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        isEligible.setForeground(new java.awt.Color(0, 0, 0));
        isEligible.setText("YES");
        isEligible.setEnabled(false);
        isEligible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isEligibleActionPerformed(evt);
            }
        });
        jPanel1.add(isEligible, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 70, 40));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 810, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        searchProfile form = new searchProfile();
        form.show();
        show(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        
        boolean isActive = editBtn.getText().equals("Save");

        if (isActive) {
            // Save button is clicked, perform save action
            firstnameTxt.setEditable(false);
            middlenameTxt.setEditable(false);
            surnameTxt.setEditable(false);
            ageTxt.setEditable(false);
            genderTxt.setEnabled(false);
            contactTxt.setEditable(false);
            addressTxt.setEditable(false);
            isEligible.setEnabled(false);
            
            String sql = "UPDATE visitor SET first_name = ?, middle_name = ?, surname = ?, sex = ?, age = ?, contact = ?,"
                    + "address = ?";
            
            try{
            PreparedStatement statement = (PreparedStatement) sql_connect.db_connect().prepareStatement(sql);
            
            }catch(SQLException e){
                
            }
            
            
            editBtn.setText("Edit");
        } else {
            // Edit button is clicked, enable editing
            firstnameTxt.setEditable(true);
            middlenameTxt.setEditable(true);
            surnameTxt.setEditable(true);
            ageTxt.setEditable(true);
            genderTxt.setEnabled(true);
            contactTxt.setEditable(true);
            addressTxt.setEditable(true);
            isEligible.setEnabled(true);
            
            editBtn.setText("Save");
        }
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(variable.firstName == "" && variable.middleName == "" && variable.surname == ""){
            variable.firstName = firstnameTxt.getText();
            variable.middleName = middlenameTxt.getText();
            variable.surname = surnameTxt.getText();
       }else{
            firstnameTxt.setText(variable.firstName);
            middlenameTxt.setText(variable.middleName);
            surnameTxt.setText(variable.surname);
            ageTxt.setText(variable.age);
            genderTxt.setSelectedItem(variable.gender);
            contactTxt.setText(variable.contactNo);
            addressTxt.setText(variable.address);
        }   
    }//GEN-LAST:event_formWindowOpened

    private void isEligibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isEligibleActionPerformed
        if (isEligible.getText().equals("YES")) {
            isEligible.setText("NO");
            String hexCode = "#ff3333"; 
            Color color = Color.decode(hexCode);
            isEligible.setBackground(color);
            isEligible.setForeground(Color.WHITE);
        } else {
            isEligible.setText("YES");
            String hexCode = "#FFFACA"; 
            Color color = Color.decode(hexCode);
            isEligible.setBackground(color);
            isEligible.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_isEligibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visitorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visitorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visitorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visitorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visitorProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField firstnameTxt;
    private javax.swing.JComboBox<String> genderTxt;
    private javax.swing.JToggleButton isEligible;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField middlenameTxt;
    private javax.swing.JTextField surnameTxt;
    // End of variables declaration//GEN-END:variables
}
